name: Containers CI builder
on:
  push:
  workflow_dispatch:

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: gh-ref-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-dependent-images:
    name: Build and push helper container images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        container:
          - jenkins-base-agent-image
          - android-rom-builder
          - postmarketos-rom-builder
            # - android-app-builder
          - android-boot-image-builder
          - android-root-image-builder
          - android-astro-super-tools
          - java-services-builder
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build images
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          context: ${{ matrix.container }}/
          tags: ${{ contains(github.ref_name, 'main') && 'latest' || github.ref_name }}-planet-${{ matrix.container }}
          containerfiles: ${{ matrix.container }}/Dockerfile

      - name: Push container
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
