name: Cosmo-CoDiOS codid Jenkins reusable workflow
on:
  workflow_call:

permissions:
  packages: write

jobs:
  build-cosmo-codid-jenkins-container-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target:
          - "aarch64-unknown-linux-musl"
          - "aarch64-linux-android"
          - "x86_64-unknown-linux-musl"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GHCR.io registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
        with:
          driver-opts: image=moby/buildkit:v0.9.1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-image-cosmo-codid-jenkins-${{ matrix.target }}

      - name: Image labelling
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: latest-cosmo-codid-jenkins-${{ matrix.target }}

      - name: Build and push image to container registry
        uses: docker/build-push-action@v4.1.0
        with:
          context: ./cosmo-codios-codid-jenkins-builder
          file: ./cosmo-codios-codid-jenkins-builder/Dockerfile.${{ matrix.target }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' && (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: REF=latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
