name: Containers CI builder
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-container-image:
    name: Build and push container images to GHCR for Planet compiling
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - android-rom
          - postmarketos-rom
          - java-services
          - astro-super-tools
          - boot-image-tools
#          - root-image-tools
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build images
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: shymega/planet-container-images
          tags: ${{ matrix.type }}
          containerfiles: ${{ matrix.type }}/Dockerfile

      - name: Push container
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: shymega
          password: ${{ secrets.GITHUB_TOKEN }}
